
package com.magicvalleyworks.remotewstarget.wsfacadeapi.simplews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleWebService", targetNamespace = "http://remotewstarget.magicvalleyworks.com/", wsdlLocation = "/wsdl/simpleWebService.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleWebService {


    /**
     * 
     * @param processDataRequest
     * @return
     *     returns com.magicvalleyworks.remotewstarget.wsfacadeapi.simplews.Data
     */
    @WebMethod(action = "http://remotewstarget.magicvalleyworks.com/SimpleWebService/processDataRequest")
    @WebResult(name = "processDataResponse", targetNamespace = "")
    @RequestWrapper(localName = "processDataRequest", targetNamespace = "http://remotewstarget.magicvalleyworks.com/", className = "com.magicvalleyworks.remotewstarget.wsfacadeapi.simplews.ProcessDataRequest")
    @ResponseWrapper(localName = "processDataResponse", targetNamespace = "http://remotewstarget.magicvalleyworks.com/", className = "com.magicvalleyworks.remotewstarget.wsfacadeapi.simplews.ProcessDataResponse")
    public Data processDataRequest(
        @WebParam(name = "processDataRequest", targetNamespace = "")
        Data processDataRequest);

}
