
package com.magicvalleyworks.remotewstarget.wsweb.services.simplews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleWebService",
        targetNamespace = "http://remotewstarget.magicvalleyworks.com/",
        wsdlLocation = "WEB-INF/wsdl/simpleWebService.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleWebService {


    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://remotewstarget.magicvalleyworks.com/SimpleWebService/processData")
    @WebResult(name = "processDataOutputType", targetNamespace = "http://remotewstarget.magicvalleyworks.com/", partName = "output")
    public String processData(
        @WebParam(name = "processDataInputType", targetNamespace = "http://remotewstarget.magicvalleyworks.com/", partName = "data")
        String data);

}
